import click

@click.group()
def cli():
    pass


@click.command()
def find_conflict():
    """ Find conflict file generated by syncthing """
    click.echo('find_conflict')


cli.add_command(find_conflict)

