import click
from sync_conflict import utils


@click.group()
def cli():
    pass


@click.command()
@click.argument('path')
def find_conflict(path):
    """ Find conflict file generated by syncthing """
    click.echo('Indexing files...')

    # get all files path
    files = utils.index_all_files(path)
    click.echo(str(len(files)) + ' files indexed')

    # display all conflict file
    conflicted_files = utils.get_sync_conflict_files(files)
    if len(conflicted_files) > 0:
        for file in conflicted_files:
            print(file)

    # display total number of conflict file
    click.echo(str(len(conflicted_files)) + ' conflict file')


cli.add_command(find_conflict)

